# Generated by Django 3.2.7 on 2022-01-05 11:58

import django.core.validators
from django.db import migrations, models
import localhost.models


class Migration(migrations.Migration):

    dependencies = [
        ('localhost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.FileField(upload_to='%Y/%m/%d/', validators=[localhost.models.file_size_img, django.core.validators.FileExtensionValidator(['jpeg', 'png', 'bmp', 'gif'], message='Ваше изображение должен быть jpeg, png, bmp, gif')]),
        ),
    ]
