# Generated by Django 3.2.7 on 2022-01-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localhost', '0002_auto_20220109_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='department',
            field=models.CharField(db_index=True, max_length=128, null=True, verbose_name='Отдел'),
        ),
    ]
