# Generated by Django 3.2.7 on 2022-01-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localhost', '0003_alter_userdata_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output_v15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(db_index=True, max_length=128, null=True, verbose_name='Отдел')),
                ('filesize', models.CharField(editable=False, max_length=100)),
                ('count_workers', models.ImageField(upload_to='')),
            ],
        ),
    ]
