# Generated by Django 3.2.7 on 2022-01-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localhost', '0004_output_v15'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output_v15',
            name='filesize',
            field=models.CharField(max_length=100),
        ),
    ]
