# Generated by Django 3.2.7 on 2022-01-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localhost', '0005_alter_output_v15_filesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output_v15',
            name='count_workers',
            field=models.IntegerField(),
        ),
    ]
