# Generated by Django 3.2.7 on 2022-01-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localhost', '0006_alter_output_v15_count_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output_v17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(db_index=True, max_length=128, null=True, verbose_name='Отдел')),
                ('filesize', models.CharField(max_length=100)),
                ('count_files', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
